#!/bin/bash

# ----------------------------------------------------------------------------------
# ------------------------ PUT YOUR RUNNING COMMAND(s) HERE ------------------------
# ----------------------------------------------------------------------------------
# ----- This sctipt is executed inside our GPU environment:
# -----     * all output files generated by `build.sh` are placed in this script's workdir
# -----     * feel free to execute `ls` form here to check the content of the workdir
# ----------------------------------------------------------------------------------
nvcc --version

# We can see what's on the execution server in the home dir:
echo "Content:"; ls

# apt update
# apt install cmake -y

export CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
# Run binary.
# CUDA_ARCH=86 pip install git+https://github.com/src-d/kmcuda.git#subdirectory=src
# python3 test.py

# ./kmeans
cd ./krulis/experimental/k-means/k-means
./k-means --N 2000000 --k 16 --dim 16 --algorithm cuda_best --iterations 1
# ./k-means --N 2000000 --k 16 --dim 64 --algorithm cuda_best --iterations 1
# ./k-means --N 2000000 --k 16 --dim 256 --algorithm cuda_best --iterations 1
# ./k-means --N 2000000 --k 16 --dim 1024 --algorithm cuda_best --iterations 1
# ./k-means --N 2000000 --k 16 --dim 4096 --algorithm cuda_best --iterations 1
