#!/bin/bash

# ----------------------------------------------------------------------------------
# ------------------------ PUT YOUR RUNNING COMMAND(s) HERE ------------------------
# ----------------------------------------------------------------------------------
# ----- This sctipt is executed inside our GPU environment:
# -----     * all output files generated by `build.sh` are placed in this script's workdir
# -----     * feel free to execute `ls` form here to check the content of the workdir
# ----------------------------------------------------------------------------------

# We can see what's on the execution server in the home dir:
echo "Content:"; ls

apt update
apt install cmake -y

export CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
# Run binary.
CUDA_ARCH=86 pip install git+https://github.com/src-d/kmcuda.git#subdirectory=src
python3 test.py

./kmeans
